FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

RUN apt-get update -yq \
    && apt-get upgrade -yq \
    && curl -fsSL https://deb.nodesource.com/setup_21.x | bash - \
    && apt-get install --no-install-recommends -yq nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*