FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG TARGETPLATFORM
ARG BUILDPLATFORM

RUN apt-get update -yq \
    && apt-get upgrade -yq 

RUN curl -fsSL https://deb.nodesource.com/setup_21.x | bash - && \
    apt-get install -y nodejs

RUN rm -rf /var/lib/apt/lists/* \
    && apt-get clean