import { EPGFileDto } from '@lib/smAPI/smapiTypes';

export const additionalOptions = [
  { EPGNumber: -1, Name: 'SD' },
  { EPGNumber: 1, Name: 'News' },
  { EPGNumber: 2, Name: 'Sports' },
  { EPGNumber: 3, Name: 'Movies' },
  { EPGNumber: 4, Name: 'Kids' },
  { EPGNumber: 5, Name: 'Music' },
  { EPGNumber: 6, Name: 'Documentary' },
  { EPGNumber: 7, Name: 'Comedy' },
  { EPGNumber: 8, Name: 'Drama' },
  { EPGNumber: 9, Name: 'Reality' },
  { EPGNumber: 10, Name: 'Sci-fi' },
  { EPGNumber: 11, Name: 'Horror' },
  { EPGNumber: 12, Name: 'Thriller' },
  { EPGNumber: 13, Name: 'Classic' },
  { EPGNumber: 14, Name: 'Cartoons' },
  { EPGNumber: 15, Name: 'History' },
  { EPGNumber: 16, Name: 'Action' },
  { EPGNumber: 17, Name: 'Adventure' },
  { EPGNumber: 18, Name: 'Mystery' },
  { EPGNumber: 19, Name: 'Biography' },
  { EPGNumber: 20, Name: 'Documentary Series' },
  { EPGNumber: 21, Name: 'Lifestyle' },
  { EPGNumber: 22, Name: 'Travel' },
  { EPGNumber: 23, Name: 'Cooking' },
  { EPGNumber: 24, Name: 'Nature' },
  { EPGNumber: 25, Name: 'Education' },
  { EPGNumber: 26, Name: 'Business' },
  { EPGNumber: 27, Name: 'News Analysis' },
  { EPGNumber: 28, Name: 'Health' },
  { EPGNumber: 29, Name: 'Technology' },
  { EPGNumber: 30, Name: 'Gaming' },
  { EPGNumber: 31, Name: 'E-Sports' },
  { EPGNumber: 32, Name: 'Virtual Reality' },
  { EPGNumber: 33, Name: 'Fashion' },
  { EPGNumber: 34, Name: 'Spiritual' },
  { EPGNumber: 35, Name: 'International' },
  { EPGNumber: 36, Name: 'Wildlife' },
  { EPGNumber: 37, Name: 'Arts' },
  { EPGNumber: 38, Name: 'Film Making' },
  { EPGNumber: 39, Name: 'DIY' },
  { EPGNumber: 40, Name: 'Gardening' },
  { EPGNumber: 41, Name: 'Investigation' },
  { EPGNumber: 42, Name: 'Legal' },
  { EPGNumber: 43, Name: 'Motivation' },
  { EPGNumber: 44, Name: 'Parenting' },
  { EPGNumber: 45, Name: 'Science' },
  { EPGNumber: 46, Name: 'Sports Analysis' },
  { EPGNumber: 47, Name: 'Veterinary' },
  { EPGNumber: 48, Name: 'Yoga' },
  { EPGNumber: 49, Name: 'Cinema Review' },
  { EPGNumber: 50, Name: 'Satire' }
] as EPGFileDto[];
