export { default as IconFromEPGIcon } from '@mui/icons-material/AddPhotoAlternateOutlined';
export { default as LogIcon } from '@mui/icons-material/AddToQueue';
export { default as AutoMatchIcon } from '@mui/icons-material/AutoAwesome';
export { default as QueueStatisIcon } from '@mui/icons-material/AutorenewSharp';
export { default as CancelIcon } from '@mui/icons-material/Cancel';
export { default as FilesEditorIcon } from '@mui/icons-material/FolderCopy';
export { default as ChannelEditorIcon } from '@mui/icons-material/FormatListBulletedSharp';
export { default as GroupIcon } from '@mui/icons-material/Groups';
export { default as HelpIcon } from '@mui/icons-material/HelpOutlineOutlined';
export { default as EPGFilecon, default as M3UFilecon } from '@mui/icons-material/InsertDriveFileOutlined';
export { default as PlayListIcon } from '@mui/icons-material/LibraryBooks';
export { default as SideBarMenuIcon } from '@mui/icons-material/Menu';
export { default as VideoIcon, default as VideoPlayerIcon } from '@mui/icons-material/OndemandVideo';
export { default as M3UPlaylistEditorIcon, default as PlayListEditorIcon } from '@mui/icons-material/PlaylistAddSharp';
export { default as ResetLogoIcon } from '@mui/icons-material/RotateLeft';
export { default as SDChannelIcon } from '@mui/icons-material/ScheduleSend';
export { default as SDIcon } from '@mui/icons-material/SendTimeExtension';
export { default as StreamGroupEditorIcon } from '@mui/icons-material/SettingsInputAntenna';
export { default as SettingsEditorIcon } from '@mui/icons-material/SettingsSharp';
export { default as StreamingStatusIcon } from '@mui/icons-material/ShowChartSharp';
