using StreamMaster.SchedulesDirect.Domain.Models;

namespace StreamMaster.Domain.Configuration;

public class SDSettings
{
    public bool SeriesPosterArt { get; set; }
    public bool SeriesWsArt { get; set; }
    public string SeriesPosterAspect { get; set; } = "4x3";
    public string ArtworkSize { get; set; } = "Md";
    public bool ExcludeCastAndCrew { get; set; } = false;
    public bool AlternateSEFormat { get; set; }
    public bool PrefixEpisodeDescription { get; set; } = true;
    public bool PrefixEpisodeTitle { get; set; } = true;
    public bool AppendEpisodeDesc { get; set; } = true;
    public int SDEPGDays { get; set; } = 7;
    public bool SDEnabled { get; set; }
    public string SDUserName { get; set; } = string.Empty;
    public string SDCountry { get; set; } = "USA";
    public string SDPassword { get; set; } = string.Empty;
    public string SDPostalCode { get; set; } = string.Empty;

    public string PreferredLogoStyle { get; set; } = "DARK";
    public string AlternateLogoStyle { get; set; } = "WHITE";


    public List<StationIdLineup> SDStationIds { get; set; } = [];
    public bool SeasonEventImages { get; set; } = true;
    public bool XmltvAddFillerData { get; set; } = true;
    //public string XmltvFillerProgramDescription { get; set; } = "This program was generated by Stream Master to provide filler data for stations that did not receive any guide listings from the upstream source.";
    public int XmltvFillerProgramLength { get; set; } = 4;
    public bool XmltvIncludeChannelNumbers { get; set; } = false;
    public bool XmltvExtendedInfoInTitleDescriptions { get; set; }
    public bool XmltvSingleImage { get; set; }
}
