// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamMasterInfrastructure.Persistence;

#nullable disable

namespace StreamMasterInfrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230602160304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("StreamMasterDomain.Entities.ChannelGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegexMatch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChannelGroups");
                });

            modelBuilder.Entity("StreamMasterDomain.Entities.EPGFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysToUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadErrors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EPGRank")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FileExists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDownloadAttempt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDownloaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumMinutesBetweenDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgrammeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SMFileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("TimeShift")
                        .HasColumnType("REAL");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EPGFiles", (string)null);
                });

            modelBuilder.Entity("StreamMasterDomain.Entities.IconFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadErrors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FileExists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDownloadAttempt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDownloaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumMinutesBetweenDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SMFileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Icons");
                });

            modelBuilder.Entity("StreamMasterDomain.Entities.M3UFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysToUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadErrors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FileExists")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDownloadAttempt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDownloaded")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxStreamCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumMinutesBetweenDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SMFileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingChannelNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("M3UFiles", (string)null);
                });

            modelBuilder.Entity("StreamMasterDomain.Entities.StreamGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamGroupNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StreamGroups");
                });

            modelBuilder.Entity("StreamMasterDomain.Entities.StreamGroupVideoStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreamGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoStreamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StreamGroupId");

                    b.HasIndex("VideoStreamId");

                    b.ToTable("StreamGroupVideoStream");
                });

            modelBuilder.Entity("StreamMasterDomain.Entities.VideoStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("M3UFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreamErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StreamLastFail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StreamLastStream")
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamProxyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tvg_ID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tvg_chno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tvg_group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tvg_logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tvg_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User_Tvg_ID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("User_Tvg_chno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User_Tvg_group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User_Tvg_logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User_Tvg_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User_Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoStreamHandler")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VideoStreams");
                });

            modelBuilder.Entity("StreamMasterDomain.Entities.VideoStreamRelationship", b =>
                {
                    b.Property<int>("ParentVideoStreamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildVideoStreamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParentVideoStreamId", "ChildVideoStreamId");

                    b.HasIndex("ChildVideoStreamId");

                    b.ToTable("VideoStreamRelationships");
                });

            modelBuilder.Entity("StreamMasterDomain.Entities.StreamGroupVideoStream", b =>
                {
                    b.HasOne("StreamMasterDomain.Entities.StreamGroup", null)
                        .WithMany()
                        .HasForeignKey("StreamGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamMasterDomain.Entities.VideoStream", null)
                        .WithMany()
                        .HasForeignKey("VideoStreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StreamMasterDomain.Entities.VideoStreamRelationship", b =>
                {
                    b.HasOne("StreamMasterDomain.Entities.VideoStream", "ChildVideoStream")
                        .WithMany("ChildRelationships")
                        .HasForeignKey("ChildVideoStreamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StreamMasterDomain.Entities.VideoStream", "ParentVideoStream")
                        .WithMany("ParentRelationships")
                        .HasForeignKey("ParentVideoStreamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChildVideoStream");

                    b.Navigation("ParentVideoStream");
                });

            modelBuilder.Entity("StreamMasterDomain.Entities.VideoStream", b =>
                {
                    b.Navigation("ChildRelationships");

                    b.Navigation("ParentRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
