//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("0.3.2.0")]
[assembly: AssemblyVersion("0.3.2.0")]
[assembly: AssemblyInformationalVersion("0.3.2-epg-love.1+38.Branch.epg-love.Sha.2739af8624e5e2c48591fcbf4585de58db0944b9")]