namespace StreamMaster.SchedulesDirect.Domain;

public enum SDHttpResponseCode
{
    OK = 0,
    INVALID_JSON = 1001,
    DEFLATE_REQUIRED = 1002,
    USERAGENT_REQUIRED = 1003,
    TOKEN_MISSING = 1004,
    TOKEN_INVALID = 1010,
    UNSUPPORTED_COMMAND = 2000,
    REQUIRED_ACTION_MISSING = 2001,
    REQUIRED_REQUEST_MISSING = 2002,
    REQUIRED_PARAMETER_MISSING_COUNTRY = 2004,
    REQUIRED_PARAMETER_MISSING_POSTALCODE = 2005,
    REQUIRED_PARAMETER_MISSING_MSGID = 2006,
    INVALID_PARAMETER_COUNTRY = 2050,
    INVALID_PARAMETER_POSTALCODE = 2051,
    INVALID_PARAMETER_FETCHTYPE = 2052,
    DUPLICATE_LINEUP = 2100,
    LINEUP_NOT_FOUND = 2101,
    UNKNOWN_LINEUP = 2102,
    INVALID_LINEUP_DELETE = 2103,
    LINEUP_WRONG_FORMAT = 2104,
    INVALID_LINEUP = 2105,
    LINEUP_DELETED = 2106,
    LINEUP_QUEUED = 2107,
    INVALID_COUNTRY = 2108,
    STATIONID_NOT_FOUND = 2200,
    SERVICE_OFFLINE = 3000,
    ACCOUNT_EXPIRED = 4001,
    INVALID_HASH = 4002,
    INVALID_USER = 4003,
    ACCOUNT_LOCKOUT = 4004,
    ACCOUNT_DISABLED = 4005,
    TOKEN_EXPIRED = 4006,
    APPLICATION_DISABLED = 4007,
    TOKEN_DUPLICATED = 4008,
    MAX_LINEUP_CHANGES_REACHED = 4100,
    MAX_LINEUPS = 4101,
    NO_LINEUPS = 4102,
    IMAGE_NOT_FOUND = 5000,
    IMAGE_QUEUED = 5001,
    MAX_IMAGE_DOWNLOADS = 5002,
    MAX_IMAGE_DOWNLOADS_TRIAL = 5003,
    UNKNOWN_USER = 5004,
    INVALID_PROGRAMID = 6000,
    PROGRAMID_QUEUED = 6001,
    SCHEDULE_NOT_FOUND = 7000,
    INVALID_SCHEDULE_REQUEST = 7010,
    SCHEDULE_RANGE_EXCEEDED = 7020,
    SCHEDULE_NOT_IN_LINEUP = 7030,
    SCHEDULE_QUEUED = 7100,
    UNKNOWN_ERROR = 9999
}

public static class SDHttpResponseCodeExtensions
{
    public static string GetMessage(this SDHttpResponseCode responseCode)
    {
        return responseCode switch
        {
            SDHttpResponseCode.OK => "OK",
            SDHttpResponseCode.INVALID_JSON => "Unable to decode JSON",
            SDHttpResponseCode.USERAGENT_REQUIRED => "USERAGENT missing from request",
            SDHttpResponseCode.DEFLATE_REQUIRED => "Did not receive Accept-Encoding: deflate in request.",
            SDHttpResponseCode.TOKEN_MISSING => "Token required but not provided in request header.",
            SDHttpResponseCode.UNSUPPORTED_COMMAND => "Unsupported command",
            SDHttpResponseCode.REQUIRED_ACTION_MISSING => "Request is missing an action to take.",
            SDHttpResponseCode.REQUIRED_REQUEST_MISSING => "Did not receive request.",
            SDHttpResponseCode.REQUIRED_PARAMETER_MISSING_COUNTRY => "In order to search for lineups, you must supply a 3-letter country parameter.",
            SDHttpResponseCode.REQUIRED_PARAMETER_MISSING_POSTALCODE => "In order to search for lineups, you must supply a postal code parameter.",
            SDHttpResponseCode.REQUIRED_PARAMETER_MISSING_MSGID => "In order to delete a message, you must supply the messageID.",
            SDHttpResponseCode.INVALID_PARAMETER_COUNTRY => "The COUNTRY parameter must be ISO-3166-1 alpha 3. See http://en.wikipedia.org/wiki/ISO_3166-1_alpha-3",
            SDHttpResponseCode.INVALID_PARAMETER_POSTALCODE => "The POSTALCODE parameter must be valid for the country you are searching. Post message to http://forums.schedulesdirect.org/viewforum.php?f=6 if you are having issues.",
            SDHttpResponseCode.INVALID_PARAMETER_FETCHTYPE => "You didn't provide a fetchtype I know how to handle.",
            SDHttpResponseCode.DUPLICATE_LINEUP => "Lineup already in account.",
            SDHttpResponseCode.LINEUP_NOT_FOUND => "Lineup not in account. Add lineup to account before requesting mapping.",
            SDHttpResponseCode.UNKNOWN_LINEUP => "Invalid lineup requested. Check your COUNTRY / POSTALCODE combination for validity.",
            SDHttpResponseCode.INVALID_LINEUP_DELETE => "Delete of lineup not in account.",
            SDHttpResponseCode.LINEUP_WRONG_FORMAT => "Lineup must be formatted COUNTRY-LINEUP-DEVICE or COUNTRY-OTA-POSTALCODE",
            SDHttpResponseCode.INVALID_LINEUP => "The lineup you submitted doesn't exist.",
            SDHttpResponseCode.LINEUP_DELETED => "The lineup you requested has been deleted from the server.",
            SDHttpResponseCode.LINEUP_QUEUED => "The lineup is being generated on the server. Please retry.",
            SDHttpResponseCode.INVALID_COUNTRY => "The country you requested is either mis-typed or does not have valid data.",
            SDHttpResponseCode.STATIONID_NOT_FOUND => "The stationID you requested is not in any of your lineups.",
            SDHttpResponseCode.SERVICE_OFFLINE => "Server offline for maintenance.",
            SDHttpResponseCode.ACCOUNT_EXPIRED => "Account expired.",
            SDHttpResponseCode.INVALID_HASH => "Password hash must be lowercase 40 character sha1_hex of password.",
            SDHttpResponseCode.INVALID_USER => "Invalid username or password.",
            SDHttpResponseCode.ACCOUNT_LOCKOUT => "Too many login failures. Locked for 15 minutes.",
            SDHttpResponseCode.ACCOUNT_DISABLED => "Account has been disabled. Please contact Schedules Direct support: admin@schedulesdirect.org for more information.",
            SDHttpResponseCode.TOKEN_EXPIRED => "Token has expired. Request new token.",
            SDHttpResponseCode.MAX_LINEUP_CHANGES_REACHED => "Exceeded maximum number of lineup changes for today.",
            SDHttpResponseCode.MAX_LINEUPS => "Exceeded number of lineups for this account.",
            SDHttpResponseCode.NO_LINEUPS => "No lineups have been added to this account.",
            SDHttpResponseCode.IMAGE_NOT_FOUND => "Could not find requested image. Post message to http://forums.schedulesdirect.org/viewforum.php?f=6 if you are having issues.",
            SDHttpResponseCode.INVALID_PROGRAMID => "Could not find requested programID. Permanent failure.",
            SDHttpResponseCode.PROGRAMID_QUEUED => "ProgramID should exist at the server, but doesn't. The server will regenerate the JSON for the program, so your application should retry.",
            SDHttpResponseCode.SCHEDULE_NOT_FOUND => "The schedule you requested should be available. Post message to http://forums.schedulesdirect.org/viewforum.php?f=6",
            SDHttpResponseCode.INVALID_SCHEDULE_REQUEST => "The server can't determine whether your schedule is valid or not. Open a support ticket.",
            SDHttpResponseCode.SCHEDULE_RANGE_EXCEEDED => "The date that you've requested is outside of the range of the data for that stationID.",
            SDHttpResponseCode.SCHEDULE_NOT_IN_LINEUP => "You have requested a schedule which is not in any of your configured lineups.",
            SDHttpResponseCode.SCHEDULE_QUEUED => "The schedule you requested has been queued for generation but is not yet ready for download. Retry.",
            SDHttpResponseCode.UNKNOWN_ERROR => "Unknown error. Open support ticket.",
            _ => "Unknown error.",
        };
    }
}